apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl 
            image: debianmaster/kubectl
            args:
            - /bin/sh
            - -c
            - kubectl set image deployments,rc store-inventory=debianmaster/store-inventory:latest --all 
          restartPolicy: Never
