kind: Template
apiVersion: v1
metadata:
  name: custom-nodejs
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: custom-nodejs
      annotations:
        description: Defines how to build the application
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}" 
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: "ImageStreamTag",
            namespace": "openshift",
            name": nodejs:4
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: custom-nodejs
    spec:
      replicas: 1
parameters:
  - name: SOURCE_REPOSITORY_URL 
    displayName: Source Repository URL 
    description: The URL of the repository with your application source code 
    value: https://github.com/debianmaster/nodejs-welcome.git 
    required: true
