kind: Template
apiVersion: v1
metadata:
  name: custom-nodejs
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      annotations:
        description: Defines how to build the application
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}" 
          ref: "master"
        contextDir: "/"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: "ImageStreamTag"
            namespace: "openshift"
            name: nodejs:4
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}" 
    spec:
      replicas: 1
      selector:
        name: "${APPLICATION_NAME}" 
      template:
        metadata:
          labels:
            name: "${APPLICATION_NAME}"
        spec:
          containers:
          - image: "${APPLICATION_NAME}"
            name: "${APPLICATION_NAME}"
            ports:
            - containerPort: 8080
              protocol: TCP
parameters:
  - name: SOURCE_REPOSITORY_URL 
    displayName: Source Repository URL 
    description: The URL of the repository with your application source code 
    value: https://github.com/debianmaster/nodejs-welcome.git 
    required: true
  - name: APPLICATION_NAME 
    displayName: Application Name 
    description: Application Name 
    value: appname 
    required: true
