apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: minio-ocp
  name: minio-ocp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: minio-ocp:latest
  source:
    dockerfile: |-
      FROM minio/minio:edge
      CMD ["server","/export"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: minio:edge
    type: Docker
status:
  lastVersion: 0
